### ISSUE TITLE
How do I prevent formatting?

### ISSUE THREAD

**Issue by ameya98** [JamesxX/typst-chem-par#4]
I have a string (say "M06") that I do not want to be formatted by `chem-par`. Is there an escape sequence I can use?

**Comment by JamesxX** [comment]
Hey :)

https://github.com/JamesxX/typst-chem-par/blob/cbfc3a1794ea0ba7b0600ca95e5595e0a8bd6e6e/src/stateful.typ#L12

This function should do what you're looking for. I'm not sure if that is in the current release on the package manager, if not, I'll bump the version tomorrow and let you know

**Comment by ameya98** [comment]
Thanks!
