### ISSUE TITLE
the n- in phrase "ten- to twenty-fold" should not be rendered italic

### ISSUE THREAD

**Issue by tilman-schieber** [JamesxX/typst-chem-par#7]
In the sentence
> This process requires a ten- to twenty-fold excess of water to suppress the formation of polyethers.

the n in ten- is rendered as italic.

**Comment by SillyFreak** [comment]
My naive fix would be to make the following change [here](https://github.com/JamesxX/typst-chem-par/blob/main/src/rules/isomers.typ#L4):
```diff
- (exo)|[iompnNO])-
+ (exo)|\b[iompnNO])-
```
But I don't know enough about nomenclature to ensure this is correct and comprehensive
